### ISSUE TITLE
初回アクセス時、カタログに何も表示されない

### ISSUE THREAD

**Issue by eiurur** [eiurur/NijiuraDeck#325]
```
vue.runtime.esm.js:1897 TypeError: this.preThreads.find is not a function
    at a.getCurrent (FavoriteThreadList.vue:170:1)
    at a.diff (FavoriteThreadList.vue:189:1)
    at ii.get (vue.runtime.esm.js:4495:25)
    at ii.evaluate (vue.runtime.esm.js:4597:21)
    at a.diff (vue.runtime.esm.js:4851:17)
    at a.J (ThreadList.vue?c61a:1:594)
    at e._render (vue.runtime.esm.js:3569:22)
    at a.i (vue.runtime.esm.js:4081:21)
    at ii.get (vue.runtime.esm.js:4495:25)
    at new ii (vue.runtime.esm.js:4484:12)
```
![image](https://user-images.githubusercontent.com/4101830/188276492-ed5a1419-0745-41b6-a271-6d6cb472062f.png)

**Comment by eiurur** [comment]
Arrayになるはずが、Objectが入っている。

![chrome_EDAsjwAiax](https://user-images.githubusercontent.com/4101830/188276818-f3d61fe0-1de2-43b6-b0df-281a8ad8a28a.png)

**Comment by eiurur** [comment]
OK
![chrome_Kf6W7PJFJI](https://user-images.githubusercontent.com/4101830/188277216-3764cdc9-2446-400e-b216-64d32285efa6.png)
